# 行列演算の基礎

$\boldsymbol{w}=(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- ベクトルの定義
- 行列の定義
- 転置
- 逆行列
- 行列積

In [1]:
import numpy as np

In [6]:
# ベクトルの定義
x = np.array([[1],[2],[3]])
print(x)

[[1]
 [2]
 [3]]


In [8]:
# 行列の定義
X = np.array([[1,2],[3,4]])
print(X)

[[1 2]
 [3 4]]


In [10]:
# 転置の計算
Xt = X.T
print(Xt)

[[1 3]
 [2 4]]


In [12]:
# 逆行列
# linear algebra: 線形代数
X_inv = np.linalg.inv(X)
print(X_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [14]:
# 行列積
XX_inv = np.dot(X,X_inv)
print(XX_inv)

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


# よくある間違い

In [17]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [18]:
x.T

array([1, 2, 3])

In [21]:
x = np.array([[1,2,3]])
x

array([[1, 2, 3]])

In [22]:
x.T

array([[1],
       [2],
       [3]])

# Numpyでよく使う処理

In [28]:
X = np.array([
    [2,3,4],
    [1,2,3]
])
print(X)

[[2 3 4]
 [1 2 3]]


In [32]:
X.shape

(2, 3)

In [29]:
row,col =X.shape

In [30]:
row

2

In [31]:
col

3

In [33]:
for x in X:
    print(x)

[2 3 4]
[1 2 3]


# 演習問題

$\boldsymbol{X} = \begin{bmatrix}
1 & 2 & 3 \\
1 & 2 & 5 \\
1 & 3 & 4 \\
1 & 5 & 9 \\
\end{bmatrix}
,\ \boldsymbol{y} = \begin{bmatrix}
1\\
5\\
6\\
8\\
\end{bmatrix}
$ のとき

$\boldsymbol{w}=(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

- Step1: $(\boldsymbol{X}^{T}\boldsymbol{X})$
- Step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$
- Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$
- Step4: $\boldsymbol{w}=(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [36]:
# Xの定義
X = np.array([
    [1,2,3],
    [1,2,5],
    [1,3,4],
    [1,5,9]
])
print(X)

[[1 2 3]
 [1 2 5]
 [1 3 4]
 [1 5 9]]


In [38]:
# yの定義
y = np.array([
    [1],
    [5],
    [6],
    [8]
])
print(y)

[[1]
 [5]
 [6]
 [8]]


## Step1: $(\boldsymbol{X}^{T}\boldsymbol{X})$

In [40]:
# Step1
XtX = np.dot(X.T,X)
print(XtX)

[[  4  12  21]
 [ 12  42  73]
 [ 21  73 131]]


## Step2: $(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}$

In [43]:
# Step2
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 1.76530612 -0.39795918 -0.06122449]
 [-0.39795918  0.84693878 -0.40816327]
 [-0.06122449 -0.40816327  0.24489796]]


## Step3: $\boldsymbol{X}^{T}\boldsymbol{y}$

In [45]:
# Step3
Xty = np.dot(X.T,y)
print(Xty)

[[ 20]
 [ 70]
 [124]]


## Step4: $\boldsymbol{w}=(\boldsymbol{X}^{T}\boldsymbol{X})^{-1}\boldsymbol{X}^{T}\boldsymbol{y}$

In [48]:
# Step4
w = np.dot(XtX_inv,Xty)
print(w)

[[-0.14285714]
 [ 0.71428571]
 [ 0.57142857]]


# Scikit-learnで実装
http://scikit-learn.org/

In [49]:
import sklearn

In [52]:
# 重回帰分析のみ読み込み
from sklearn.linear_model import LinearRegression

In [53]:
# モデルの宣言
model = LinearRegression()

In [54]:
# モデルの学習 ← パラメータの調整
model.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [55]:
# 調整後のパラメータ
model.coef_ #重み

array([[0.        , 0.71428571, 0.57142857]])

In [57]:
model.intercept_ #切片

array([-0.14285714])

In [59]:
# 切片を含む場合
model2 = LinearRegression(fit_intercept=False)
model2.fit(X,y)
print(model2.coef_)
print(model2.intercept_)

[[-0.14285714  0.71428571  0.57142857]]
0.0


In [60]:
# 予測精度 ← 決定係数
model.score(X,y)

0.6923076923076926

In [61]:
# 予測値の計算
x = np.array([[1,2,3]])

In [62]:
model.predict(x)

array([[3.]])